---

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

# Fully quoted because of the ': ' on the line. See the Gotchas in the YAML docs.
- name: Remove password prompt for sudo
  lineinfile: "dest=/etc/sudoers state=present regexp='^%wheel' line='%wheel ALL=(ALL) NOPASSWD: ALL'"
