---

- import_tasks: ubuntu-setup.yml
  when: ansible_distribution == "Ubuntu"

- import_tasks: centos-setup.yml
  when: ansible_distribution == "Centos"


# Set Time Zone
- name: Set timezone
  timezone: name={{ timezone }}
