---

- include: ubuntu-setup.yml
  when: ansible_distribution == "Ubuntu"

- include: centos-setup.yml
  when: ansible_distribution == "Centos"


# Set Time Zone
- name: Set timezone
  timezone: name={{ timezone }}
